# Site settings
title: Neuro Madness
name: NeuroMadness
email: info@neuromadness.org
location: Naples, FL
company: NeuroMadness
company_url: http://neuromadness.org
github_url: neuromadnessorg
description: What is going on?
favicon: favicon.png # Image must be in assets/images
repository: neuromadnessorg/neuromadnessorg.github.io

# url: https://neuromadnessorg.github.io
url: http://localhost:4000

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# Disque
disque: neuromadness.disqus.com

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation. To be extended
navs:
  -
    href: /
    label: Home

  -
    href: /articles
    label: Articles

  -
    href: /about
    label: About

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'UA-98611517-1'  # ex. UA-72165600-X
